apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-default
spec:
  hosts:
    - coffee-service
  http:
    - route:
        - destination:
            host: coffee-service
            subset: v1
