##################################################################################################
# Coffee service
##################################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-service
  labels:
    app: coffee-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coffee-service
        version: "1.0"
        serving: "true"
    spec:
      containers:
        - name: coffee-service
          image: sbishyr/coffee-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-service
  labels:
    app: coffee-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: coffee-service
    serving: "true"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coffee-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: coffee-service
              servicePort: 8080
#          - path: /discounted
#            backend:
#              serviceName: my-discounted-products
#              servicePort: 80
